folder directory re-arrange added back secure store
BEE-Capstone-2024/Front-End-GreenCircle pull request #5
Opened 2024-06-17 18:22 UTC by andysu1126

re-arrange (tabs) into (auth) folder so the frontend security logic could work
added back secure store to store jwt token
Logged-in users or users who have jwt token in the cache will be re route to the home page now.

2024-06-17 20:19 UTC, eemraydin requested changes

2024-06-17 20:19 UTC, eemraydin commented on app/_layout.jsx
> +      router.replace("/(tabs)/home");
I was looking for securing files but in app file all files are in same level of access. Please check the documentation below. It doesn't make sense to put tabs in same level of sign in and sign up page. Please try to keep them in different file root. We should control route access beside file structure.

https://docs.expo.dev/router/reference/authentication/

2024-06-17 22:50 UTC, andysu1126 commented on app/_layout.jsx
> +      router.replace("/(tabs)/home");
what if I create a (public) folder under app folder and move login.jsx, register.jsx in it because (tabs) is supposed to be inside (auth). the (auth) means authenticated, so only authenticated users are allow to have access to tabs.

2024-06-18 03:43 UTC, eemraydin approved these changes

2024-06-18 03:43 UTC, merged